// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/telemetry.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Countercept.Shared.Protobuf {

  /// <summary>Holder for reflection information generated from proto/telemetry.proto</summary>
  public static partial class TelemetryReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/telemetry.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TelemetryReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVwcm90by90ZWxlbWV0cnkucHJvdG8SC2NvdW50ZXJjZXB0Gh9nb29nbGUv",
            "cHJvdG9idWYvdGltZXN0YW1wLnByb3RvIsACCghFdHdFdmVudBISCgpldmVu",
            "dF91dWlkGAEgASgJEi0KCXRpbWVzdGFtcBgCIAEoCzIaLmdvb2dsZS5wcm90",
            "b2J1Zi5UaW1lc3RhbXASFAoMbWFjaGluZV9uYW1lGAMgASgJEhUKDXByb3Zp",
            "ZGVyX25hbWUYBCABKAkSEAoIZXZlbnRfaWQYBSABKA0SEgoKcHJvY2Vzc19p",
            "ZBgGIAEoDRIRCgl0aHJlYWRfaWQYByABKA0SEQoJdGFza19uYW1lGAggASgJ",
            "EhMKC29wY29kZV9uYW1lGAkgASgJEjMKB3BheWxvYWQYCiADKAsyIi5jb3Vu",
            "dGVyY2VwdC5FdHdFdmVudC5QYXlsb2FkRW50cnkaLgoMUGF5bG9hZEVudHJ5",
            "EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAFCHqoCG0NvdW50ZXJj",
            "ZXB0LlNoYXJlZC5Qcm90b2J1ZmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Countercept.Shared.Protobuf.EtwEvent), global::Countercept.Shared.Protobuf.EtwEvent.Parser, new[]{ "EventUuid", "Timestamp", "MachineName", "ProviderName", "EventId", "ProcessId", "ThreadId", "TaskName", "OpcodeName", "Payload" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class EtwEvent : pb::IMessage<EtwEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EtwEvent> _parser = new pb::MessageParser<EtwEvent>(() => new EtwEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EtwEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Countercept.Shared.Protobuf.TelemetryReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EtwEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EtwEvent(EtwEvent other) : this() {
      eventUuid_ = other.eventUuid_;
      timestamp_ = other.timestamp_ != null ? other.timestamp_.Clone() : null;
      machineName_ = other.machineName_;
      providerName_ = other.providerName_;
      eventId_ = other.eventId_;
      processId_ = other.processId_;
      threadId_ = other.threadId_;
      taskName_ = other.taskName_;
      opcodeName_ = other.opcodeName_;
      payload_ = other.payload_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EtwEvent Clone() {
      return new EtwEvent(this);
    }

    /// <summary>Field number for the "event_uuid" field.</summary>
    public const int EventUuidFieldNumber = 1;
    private string eventUuid_ = "";
    /// <summary>
    /// Unique ID for the event instance
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EventUuid {
      get { return eventUuid_; }
      set {
        eventUuid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timestamp_;
    /// <summary>
    /// The precise time the event occurred on the host
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "machine_name" field.</summary>
    public const int MachineNameFieldNumber = 3;
    private string machineName_ = "";
    /// <summary>
    /// The name of the host (e.g., "WIN-WORKSTATION-01")
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MachineName {
      get { return machineName_; }
      set {
        machineName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "provider_name" field.</summary>
    public const int ProviderNameFieldNumber = 4;
    private string providerName_ = "";
    /// <summary>
    /// The ETW Provider (e.g., "Microsoft-Windows-Kernel-Process")
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ProviderName {
      get { return providerName_; }
      set {
        providerName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "event_id" field.</summary>
    public const int EventIdFieldNumber = 5;
    private uint eventId_;
    /// <summary>
    /// The specific Event ID (e.g., 1 for Process Start)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint EventId {
      get { return eventId_; }
      set {
        eventId_ = value;
      }
    }

    /// <summary>Field number for the "process_id" field.</summary>
    public const int ProcessIdFieldNumber = 6;
    private uint processId_;
    /// <summary>
    /// Contextual IDs
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ProcessId {
      get { return processId_; }
      set {
        processId_ = value;
      }
    }

    /// <summary>Field number for the "thread_id" field.</summary>
    public const int ThreadIdFieldNumber = 7;
    private uint threadId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ThreadId {
      get { return threadId_; }
      set {
        threadId_ = value;
      }
    }

    /// <summary>Field number for the "task_name" field.</summary>
    public const int TaskNameFieldNumber = 8;
    private string taskName_ = "";
    /// <summary>
    /// The opcode name (e.g., "Info", "Start", "Stop")
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TaskName {
      get { return taskName_; }
      set {
        taskName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "opcode_name" field.</summary>
    public const int OpcodeNameFieldNumber = 9;
    private string opcodeName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OpcodeName {
      get { return opcodeName_; }
      set {
        opcodeName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 10;
    private static readonly pbc::MapField<string, string>.Codec _map_payload_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 82);
    private readonly pbc::MapField<string, string> payload_ = new pbc::MapField<string, string>();
    /// <summary>
    /// --- Dynamic Payload Data ---
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> Payload {
      get { return payload_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EtwEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EtwEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EventUuid != other.EventUuid) return false;
      if (!object.Equals(Timestamp, other.Timestamp)) return false;
      if (MachineName != other.MachineName) return false;
      if (ProviderName != other.ProviderName) return false;
      if (EventId != other.EventId) return false;
      if (ProcessId != other.ProcessId) return false;
      if (ThreadId != other.ThreadId) return false;
      if (TaskName != other.TaskName) return false;
      if (OpcodeName != other.OpcodeName) return false;
      if (!Payload.Equals(other.Payload)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EventUuid.Length != 0) hash ^= EventUuid.GetHashCode();
      if (timestamp_ != null) hash ^= Timestamp.GetHashCode();
      if (MachineName.Length != 0) hash ^= MachineName.GetHashCode();
      if (ProviderName.Length != 0) hash ^= ProviderName.GetHashCode();
      if (EventId != 0) hash ^= EventId.GetHashCode();
      if (ProcessId != 0) hash ^= ProcessId.GetHashCode();
      if (ThreadId != 0) hash ^= ThreadId.GetHashCode();
      if (TaskName.Length != 0) hash ^= TaskName.GetHashCode();
      if (OpcodeName.Length != 0) hash ^= OpcodeName.GetHashCode();
      hash ^= Payload.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EventUuid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(EventUuid);
      }
      if (timestamp_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Timestamp);
      }
      if (MachineName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(MachineName);
      }
      if (ProviderName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ProviderName);
      }
      if (EventId != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(EventId);
      }
      if (ProcessId != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(ProcessId);
      }
      if (ThreadId != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(ThreadId);
      }
      if (TaskName.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(TaskName);
      }
      if (OpcodeName.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(OpcodeName);
      }
      payload_.WriteTo(output, _map_payload_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EventUuid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(EventUuid);
      }
      if (timestamp_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Timestamp);
      }
      if (MachineName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(MachineName);
      }
      if (ProviderName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ProviderName);
      }
      if (EventId != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(EventId);
      }
      if (ProcessId != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(ProcessId);
      }
      if (ThreadId != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(ThreadId);
      }
      if (TaskName.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(TaskName);
      }
      if (OpcodeName.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(OpcodeName);
      }
      payload_.WriteTo(ref output, _map_payload_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EventUuid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EventUuid);
      }
      if (timestamp_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Timestamp);
      }
      if (MachineName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MachineName);
      }
      if (ProviderName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ProviderName);
      }
      if (EventId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EventId);
      }
      if (ProcessId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ProcessId);
      }
      if (ThreadId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ThreadId);
      }
      if (TaskName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TaskName);
      }
      if (OpcodeName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OpcodeName);
      }
      size += payload_.CalculateSize(_map_payload_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EtwEvent other) {
      if (other == null) {
        return;
      }
      if (other.EventUuid.Length != 0) {
        EventUuid = other.EventUuid;
      }
      if (other.timestamp_ != null) {
        if (timestamp_ == null) {
          Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Timestamp.MergeFrom(other.Timestamp);
      }
      if (other.MachineName.Length != 0) {
        MachineName = other.MachineName;
      }
      if (other.ProviderName.Length != 0) {
        ProviderName = other.ProviderName;
      }
      if (other.EventId != 0) {
        EventId = other.EventId;
      }
      if (other.ProcessId != 0) {
        ProcessId = other.ProcessId;
      }
      if (other.ThreadId != 0) {
        ThreadId = other.ThreadId;
      }
      if (other.TaskName.Length != 0) {
        TaskName = other.TaskName;
      }
      if (other.OpcodeName.Length != 0) {
        OpcodeName = other.OpcodeName;
      }
      payload_.MergeFrom(other.payload_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            EventUuid = input.ReadString();
            break;
          }
          case 18: {
            if (timestamp_ == null) {
              Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Timestamp);
            break;
          }
          case 26: {
            MachineName = input.ReadString();
            break;
          }
          case 34: {
            ProviderName = input.ReadString();
            break;
          }
          case 40: {
            EventId = input.ReadUInt32();
            break;
          }
          case 48: {
            ProcessId = input.ReadUInt32();
            break;
          }
          case 56: {
            ThreadId = input.ReadUInt32();
            break;
          }
          case 66: {
            TaskName = input.ReadString();
            break;
          }
          case 74: {
            OpcodeName = input.ReadString();
            break;
          }
          case 82: {
            payload_.AddEntriesFrom(input, _map_payload_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            EventUuid = input.ReadString();
            break;
          }
          case 18: {
            if (timestamp_ == null) {
              Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Timestamp);
            break;
          }
          case 26: {
            MachineName = input.ReadString();
            break;
          }
          case 34: {
            ProviderName = input.ReadString();
            break;
          }
          case 40: {
            EventId = input.ReadUInt32();
            break;
          }
          case 48: {
            ProcessId = input.ReadUInt32();
            break;
          }
          case 56: {
            ThreadId = input.ReadUInt32();
            break;
          }
          case 66: {
            TaskName = input.ReadString();
            break;
          }
          case 74: {
            OpcodeName = input.ReadString();
            break;
          }
          case 82: {
            payload_.AddEntriesFrom(ref input, _map_payload_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
