# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/telemetry.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'proto/telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/telemetry.proto\x12\x0b\x63ountercept\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc0\x02\n\x08\x45twEvent\x12\x12\n\nevent_uuid\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x14\n\x0cmachine_name\x18\x03 \x01(\t\x12\x15\n\rprovider_name\x18\x04 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x05 \x01(\r\x12\x12\n\nprocess_id\x18\x06 \x01(\r\x12\x11\n\tthread_id\x18\x07 \x01(\r\x12\x11\n\ttask_name\x18\x08 \x01(\t\x12\x13\n\x0bopcode_name\x18\t \x01(\t\x12\x33\n\x07payload\x18\n \x03(\x0b\x32\".countercept.EtwEvent.PayloadEntry\x1a.\n\x0cPayloadEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x1e\xaa\x02\x1b\x43ountercept.Shared.Protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\033Countercept.Shared.Protobuf'
  _globals['_ETWEVENT_PAYLOADENTRY']._loaded_options = None
  _globals['_ETWEVENT_PAYLOADENTRY']._serialized_options = b'8\001'
  _globals['_ETWEVENT']._serialized_start=72
  _globals['_ETWEVENT']._serialized_end=392
  _globals['_ETWEVENT_PAYLOADENTRY']._serialized_start=346
  _globals['_ETWEVENT_PAYLOADENTRY']._serialized_end=392
# @@protoc_insertion_point(module_scope)
